"""MCP server for GitHub issue management."""

from __future__ import annotations

import httpx
from mcp.server.fastmcp import FastMCP  # type: ignore[import-not-found]

mcp = FastMCP("canopy-github")


@mcp.tool()  # type: ignore[misc,untyped-decorator]
def create_issue(
    github_token: str,
    github_repo: str,
    title: str,
    body: str,
    labels: list[str] | None = None,
) -> dict[str, object]:
    """Create a GitHub issue.

    Args:
        github_token: GitHub personal access token.
        github_repo: Repository in owner/repo format.
        title: Issue title.
        body: Issue body (markdown).
        labels: Optional list of labels to add.
    """
    payload: dict[str, object] = {"title": title, "body": body}
    if labels:
        payload["labels"] = labels

    try:
        response = httpx.post(
            f"https://api.github.com/repos/{github_repo}/issues",
            json=payload,
            headers={
                "Authorization": f"Bearer {github_token}",
                "Accept": "application/vnd.github+json",
            },
            timeout=10,
        )
        response.raise_for_status()
        data = response.json()
        return {
            "success": True,
            "issue_number": data.get("number"),
            "html_url": data.get("html_url", ""),
        }
    except httpx.HTTPError as e:
        return {"success": False, "error": str(e)}


@mcp.tool()  # type: ignore[misc,untyped-decorator]
def create_optimization_issue(
    github_token: str,
    github_repo: str,
    workload_id: str,
    workload_name: str,
    recommendation_type: str,
    reason: str,
    cost_savings_usd: float,
    carbon_savings_kg: float,
) -> dict[str, object]:
    """Create a GitHub issue for a Canopy optimization recommendation.

    Args:
        github_token: GitHub personal access token.
        github_repo: Repository in owner/repo format.
        workload_id: ID of the workload.
        workload_name: Name of the workload.
        recommendation_type: Type (idle, rightsize, region_move).
        reason: Explanation of the recommendation.
        cost_savings_usd: Estimated monthly cost savings.
        carbon_savings_kg: Estimated monthly carbon savings.
    """
    title = f"Canopy: {recommendation_type} — {workload_name}"
    body = (
        f"## Optimization Recommendation\n\n"
        f"| Field | Value |\n"
        f"|-------|-------|\n"
        f"| Workload | `{workload_name}` (`{workload_id}`) |\n"
        f"| Type | {recommendation_type} |\n"
        f"| Reason | {reason} |\n"
        f"| Cost Savings | ${cost_savings_usd:,.2f}/mo |\n"
        f"| Carbon Savings | {carbon_savings_kg:,.1f} kg CO₂/mo |\n\n"
        f"---\n"
        f"Approve by commenting `/canopy approve` on this issue.\n\n"
        f"*Generated by [Canopy Cloud](https://github.com/mahabubul470/canopy-cloud)*"
    )

    result: dict[str, object] = create_issue(
        github_token=github_token,
        github_repo=github_repo,
        title=title,
        body=body,
        labels=["canopy", "optimization"],
    )
    return result
